coverage:
  status:
    project:
      default: false
      backend:
        flags:
          - backend
        target: auto
        informational: true
      frontend:
        flags:
          - frontend
        target: auto
        informational: true
    patch:
      default:
        informational: true

flags:
  backend:
    paths:
      - backend/app/
  frontend:
    paths:
      - frontend/src/

comment: false
