// This file is auto-generated by @hey-api/openapi-ts

export const ApiKeyCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        scopes: {
            items: {
                type: 'string',
                enum: [
                    'ledger:read',
                    'ledger:write'
                ]
            },
            type: 'array',
            minItems: 1,
            uniqueItems: true,
            title: 'Scopes'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    required: [
        'name',
        'scopes'
    ],
    title: 'ApiKeyCreate'
} as const;

export const ApiKeyCreatedSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        key_prefix: {
            type: 'string',
            title: 'Key Prefix'
        },
        scopes: {
            items: {
                type: 'string',
                enum: [
                    'ledger:read',
                    'ledger:write'
                ]
            },
            type: 'array',
            title: 'Scopes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'key_prefix',
        'scopes',
        'created_at',
        'last_used_at',
        'expires_at',
        'revoked_at',
        'created_by_user_id',
        'key'
    ],
    title: 'ApiKeyCreated'
} as const;

export const ApiKeyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        key_prefix: {
            type: 'string',
            title: 'Key Prefix'
        },
        scopes: {
            items: {
                type: 'string',
                enum: [
                    'ledger:read',
                    'ledger:write'
                ]
            },
            type: 'array',
            title: 'Scopes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'key_prefix',
        'scopes',
        'created_at',
        'last_used_at',
        'expires_at',
        'revoked_at',
        'created_by_user_id'
    ],
    title: 'ApiKeyPublic'
} as const;

export const ApiKeysPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ApiKeyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ApiKeysPublic'
} as const;

export const BillingPeriodInputSchema = {
    properties: {
        year: {
            type: 'integer',
            maximum: 9999,
            minimum: 1,
            title: 'Year'
        },
        month: {
            type: 'integer',
            maximum: 12,
            minimum: 1,
            title: 'Month'
        }
    },
    type: 'object',
    required: [
        'year',
        'month'
    ],
    title: 'BillingPeriodInput'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CategoriesPublic'
} as const;

export const CategoryAmountHistoryPointPublicSchema = {
    properties: {
        period: {
            $ref: '#/components/schemas/ObligationPeriodPublic'
        },
        state: {
            type: 'string',
            enum: [
                'missing',
                'unknown',
                'known'
            ],
            title: 'State'
        },
        current_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        }
    },
    type: 'object',
    required: [
        'period',
        'state',
        'current_amount',
        'currency'
    ],
    title: 'CategoryAmountHistoryPointPublic',
    description: 'A period\'s amount, keeping missing and unknown values distinct.'
} as const;

export const CategoryAmountHistoryPublicSchema = {
    properties: {
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        points: {
            items: {
                $ref: '#/components/schemas/CategoryAmountHistoryPointPublic'
            },
            type: 'array',
            title: 'Points'
        }
    },
    type: 'object',
    required: [
        'category_id',
        'points'
    ],
    title: 'CategoryAmountHistoryPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        category_group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Group Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        code: {
            type: 'string',
            maxLength: 4,
            minLength: 4,
            pattern: '^[A-Z]{4}$',
            title: 'Code'
        },
        data_source_policy: {
            $ref: '#/components/schemas/DataSourcePolicy',
            default: 'hybrid'
        },
        recurrence_interval: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Interval'
        },
        recurrence_unit: {
            anyOf: [
                {
                    $ref: '#/components/schemas/RecurrenceUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        first_due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Due Date'
        },
        currency: {
            $ref: '#/components/schemas/Currency',
            default: 'PLN'
        }
    },
    type: 'object',
    required: [
        'category_group_id',
        'name',
        'code'
    ],
    title: 'CategoryCreate'
} as const;

export const CategoryDataRecordCreateSchema = {
    properties: {
        observed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Observed At'
        },
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'observed_at',
        'data'
    ],
    title: 'CategoryDataRecordCreate'
} as const;

export const CategoryDataRecordPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        schema_version: {
            type: 'integer',
            title: 'Schema Version'
        },
        observed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Observed At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'schema_version',
        'observed_at',
        'created_at',
        'data',
        'source',
        'external_id'
    ],
    title: 'CategoryDataRecordPublic'
} as const;

export const CategoryDataRecordsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CategoryDataRecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CategoryDataRecordsPublic'
} as const;

export const CategoryDataSchemaCreateSchema = {
    properties: {
        schema: {
            additionalProperties: true,
            type: 'object',
            title: 'Definition'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'schema'
    ],
    title: 'CategoryDataSchemaCreate'
} as const;

export const CategoryDataSchemaPublicSchema = {
    properties: {
        version: {
            type: 'integer'
        },
        schema: {
            additionalProperties: true,
            type: 'object'
        },
        is_active: {
            type: 'boolean'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    type: 'object',
    required: [
        'version',
        'schema',
        'is_active',
        'created_at'
    ]
} as const;

export const CategoryDataSchemasPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CategoryDataSchemaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CategoryDataSchemasPublic'
} as const;

export const CategoryGroupCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'CategoryGroupCreate'
} as const;

export const CategoryGroupPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: [
        'id',
        'ledger_id',
        'name',
        'description',
        'is_active',
        'archived_at'
    ],
    title: 'CategoryGroupPublic'
} as const;

export const CategoryGroupUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'CategoryGroupUpdate'
} as const;

export const CategoryGroupsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CategoryGroupPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CategoryGroupsPublic'
} as const;

export const CategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        category_group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Group Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        data_source_policy: {
            $ref: '#/components/schemas/DataSourcePolicy'
        },
        recurrence_interval: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Interval'
        },
        recurrence_unit: {
            anyOf: [
                {
                    $ref: '#/components/schemas/RecurrenceUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        first_due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Due Date'
        },
        currency: {
            $ref: '#/components/schemas/Currency'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        },
        has_data_schema: {
            type: 'boolean',
            title: 'Has Data Schema'
        },
        active_data_schema_version: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Data Schema Version'
        }
    },
    type: 'object',
    required: [
        'id',
        'ledger_id',
        'category_group_id',
        'name',
        'description',
        'is_active',
        'code',
        'data_source_policy',
        'recurrence_interval',
        'recurrence_unit',
        'first_due_date',
        'currency',
        'archived_at',
        'has_data_schema',
        'active_data_schema_version'
    ],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        category_group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Group Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        data_source_policy: {
            $ref: '#/components/schemas/DataSourcePolicy'
        },
        recurrence_interval: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Interval'
        },
        recurrence_unit: {
            anyOf: [
                {
                    $ref: '#/components/schemas/RecurrenceUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        first_due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Due Date'
        },
        currency: {
            $ref: '#/components/schemas/Currency',
            default: 'PLN'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'name',
        'data_source_policy'
    ],
    title: 'CategoryUpdate'
} as const;

export const CurrencySchema = {
    type: 'string',
    enum: [
        'PLN',
        'EUR',
        'USD',
        'GBP',
        'CHF'
    ],
    title: 'Currency'
} as const;

export const CurrencyCashflowPublicSchema = {
    properties: {
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        total_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Known Amount'
        },
        scheduled_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Scheduled Known Amount'
        },
        unscheduled_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unscheduled Known Amount'
        },
        overdue_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Overdue Known Amount'
        },
        daily: {
            items: {
                $ref: '#/components/schemas/DailyCashflowPublic'
            },
            type: 'array',
            title: 'Daily'
        }
    },
    type: 'object',
    required: [
        'currency',
        'total_known_amount',
        'scheduled_known_amount',
        'unscheduled_known_amount',
        'overdue_known_amount',
        'daily'
    ],
    title: 'CurrencyCashflowPublic',
    description: 'Amounts are grouped by currency and are never converted or combined.'
} as const;

export const CurrencyPaymentSummaryPublicSchema = {
    properties: {
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        total_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Known Amount'
        },
        paid_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Paid Known Amount'
        },
        paid_percentage: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid Percentage'
        }
    },
    type: 'object',
    required: [
        'currency',
        'total_known_amount',
        'paid_known_amount',
        'paid_percentage'
    ],
    title: 'CurrencyPaymentSummaryPublic',
    description: 'Amounts are grouped by currency and are never converted or combined.'
} as const;

export const CurrencyPeriodTotalPublicSchema = {
    properties: {
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        total_known_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Known Amount'
        }
    },
    type: 'object',
    required: [
        'currency',
        'total_known_amount'
    ],
    title: 'CurrencyPeriodTotalPublic',
    description: 'Known amounts are grouped by currency and are never converted or combined.'
} as const;

export const CurrentValueSourceSchema = {
    type: 'string',
    enum: [
        'unknown',
        'automatic',
        'manual',
        'integration',
        'legacy'
    ],
    title: 'CurrentValueSource'
} as const;

export const DailyCashflowPublicSchema = {
    properties: {
        due_date: {
            type: 'string',
            format: 'date',
            title: 'Due Date'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        cumulative_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Cumulative Amount'
        },
        is_overdue: {
            type: 'boolean',
            title: 'Is Overdue'
        }
    },
    type: 'object',
    required: [
        'due_date',
        'amount',
        'cumulative_amount',
        'is_overdue'
    ],
    title: 'DailyCashflowPublic'
} as const;

export const DataSourcePolicySchema = {
    type: 'string',
    enum: [
        'manual',
        'automatic',
        'hybrid'
    ],
    title: 'DataSourcePolicy'
} as const;

export const EffectiveValueSourceModeSchema = {
    type: 'string',
    enum: [
        'unknown',
        'automatic',
        'manual',
        'integration',
        'legacy',
        'mixed'
    ],
    title: 'EffectiveValueSourceMode'
} as const;

export const EnsuredObligationsPublicSchema = {
    properties: {
        created_keys: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Created Keys'
        },
        created_count: {
            type: 'integer',
            title: 'Created Count'
        }
    },
    type: 'object',
    required: [
        'created_keys',
        'created_count'
    ],
    title: 'EnsuredObligationsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IntegrationCreateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 64,
            pattern: '^[a-z][a-z0-9-]{0,63}$',
            title: 'Key'
        },
        provider: {
            type: 'string',
            maxLength: 64,
            pattern: '^[a-z][a-z0-9-]{0,63}$',
            title: 'Provider'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            pattern: '\\S',
            title: 'Name'
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 100,
            title: 'Category Ids'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        stale_after_seconds: {
            type: 'integer',
            maximum: 2147483647,
            exclusiveMinimum: 0,
            title: 'Stale After Seconds',
            default: 93600
        },
        run_timeout_seconds: {
            type: 'integer',
            maximum: 2147483647,
            exclusiveMinimum: 0,
            title: 'Run Timeout Seconds',
            default: 1800
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'key',
        'provider',
        'name'
    ],
    title: 'IntegrationCreate'
} as const;

export const IntegrationExecutionStateSchema = {
    type: 'string',
    enum: [
        'never_run',
        'running',
        'timed_out',
        'finished'
    ],
    title: 'IntegrationExecutionState'
} as const;

export const IntegrationHealthSchema = {
    type: 'string',
    enum: [
        'disabled',
        'timed_out',
        'stale',
        'running',
        'never_run',
        'error',
        'healthy'
    ],
    title: 'IntegrationHealth'
} as const;

export const IntegrationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        enabled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled At'
        },
        stale_after_seconds: {
            type: 'integer',
            title: 'Stale After Seconds'
        },
        run_timeout_seconds: {
            type: 'integer',
            title: 'Run Timeout Seconds'
        },
        revision: {
            type: 'integer',
            title: 'Revision'
        },
        current_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Run Id'
        },
        current_started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Started At'
        },
        current_finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Finished At'
        },
        last_finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Finished At'
        },
        last_result: {
            anyOf: [
                {
                    $ref: '#/components/schemas/IntegrationResult'
                },
                {
                    type: 'null'
                }
            ]
        },
        last_changes_detected: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Changes Detected'
        },
        last_error_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error Code'
        },
        last_error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error Message'
        },
        last_success_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Success At'
        },
        execution_state: {
            $ref: '#/components/schemas/IntegrationExecutionState'
        },
        is_stale: {
            type: 'boolean',
            title: 'Is Stale'
        },
        health: {
            $ref: '#/components/schemas/IntegrationHealth'
        }
    },
    type: 'object',
    required: [
        'id',
        'ledger_id',
        'key',
        'provider',
        'name',
        'category_ids',
        'enabled',
        'created_at',
        'updated_at',
        'enabled_at',
        'stale_after_seconds',
        'run_timeout_seconds',
        'revision',
        'current_run_id',
        'current_started_at',
        'current_finished_at',
        'last_finished_at',
        'last_result',
        'last_changes_detected',
        'last_error_code',
        'last_error_message',
        'last_success_at',
        'execution_state',
        'is_stale',
        'health'
    ],
    title: 'IntegrationPublic'
} as const;

export const IntegrationResultSchema = {
    type: 'string',
    enum: [
        'success',
        'failure'
    ],
    title: 'IntegrationResult'
} as const;

export const IntegrationRunErrorSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            pattern: '^[a-z][a-z0-9_]*$',
            title: 'Code'
        },
        message: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            pattern: '\\S',
            title: 'Message',
            description: 'Sanitized summary only; never credentials, raw responses or tracebacks.'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'code',
        'message'
    ],
    title: 'IntegrationRunError'
} as const;

export const IntegrationRunFinishSchema = {
    properties: {
        run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Run Id'
        },
        result: {
            $ref: '#/components/schemas/IntegrationResult'
        },
        changes_detected: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changes Detected'
        },
        error: {
            anyOf: [
                {
                    $ref: '#/components/schemas/IntegrationRunError'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'run_id',
        'result',
        'changes_detected',
        'error'
    ],
    title: 'IntegrationRunFinish'
} as const;

export const IntegrationRunStartSchema = {
    properties: {
        run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Run Id'
        },
        expected_revision: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: 0,
            title: 'Expected Revision'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'run_id',
        'expected_revision'
    ],
    title: 'IntegrationRunStart'
} as const;

export const IntegrationUpdateSchema = {
    properties: {
        expected_revision: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: 0,
            title: 'Expected Revision'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1,
                    pattern: '\\S'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        category_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array',
                    maxItems: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Ids'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        },
        stale_after_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 2147483647,
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stale After Seconds'
        },
        run_timeout_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 2147483647,
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Run Timeout Seconds'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'expected_revision'
    ],
    title: 'IntegrationUpdate'
} as const;

export const IntegrationsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/IntegrationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'IntegrationsPublic'
} as const;

export const LedgerAccessRoleSchema = {
    type: 'string',
    enum: [
        'owner',
        'editor',
        'viewer'
    ],
    title: 'LedgerAccessRole'
} as const;

export const LedgerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'LedgerCreate'
} as const;

export const LedgerMemberPublicSchema = {
    properties: {
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            $ref: '#/components/schemas/LedgerAccessRole'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'ledger_id',
        'user_id',
        'email',
        'full_name',
        'role',
        'created_at'
    ],
    title: 'LedgerMemberPublic'
} as const;

export const LedgerMemberUpdateSchema = {
    properties: {
        role: {
            $ref: '#/components/schemas/LedgerAccessRole'
        }
    },
    type: 'object',
    required: [
        'role'
    ],
    title: 'LedgerMemberUpdate'
} as const;

export const LedgerMembersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/LedgerMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'LedgerMembersPublic'
} as const;

export const LedgerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner User Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'owner_user_id',
        'name',
        'description',
        'created_at',
        'updated_at'
    ],
    title: 'LedgerPublic'
} as const;

export const LedgerShareSchema = {
    properties: {
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        role: {
            $ref: '#/components/schemas/LedgerAccessRole'
        }
    },
    type: 'object',
    required: [
        'role'
    ],
    title: 'LedgerShare'
} as const;

export const LedgerUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'LedgerUpdate'
} as const;

export const LedgersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/LedgerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'LedgersPublic'
} as const;

export const LegacyImportJobPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        status: {
            $ref: '#/components/schemas/LegacyImportJobStatus'
        },
        processed_obligations: {
            type: 'integer',
            title: 'Processed Obligations'
        },
        total_obligations: {
            type: 'integer',
            title: 'Total Obligations'
        },
        created_category_groups: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created Category Groups'
        },
        created_categories: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created Categories'
        },
        replaced_categories: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Replaced Categories'
        },
        imported_obligations: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Obligations'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: [
        'id',
        'ledger_id',
        'status',
        'processed_obligations',
        'total_obligations',
        'created_category_groups',
        'created_categories',
        'replaced_categories',
        'imported_obligations',
        'error',
        'created_at',
        'started_at',
        'finished_at'
    ],
    title: 'LegacyImportJobPublic'
} as const;

export const LegacyImportJobStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'running',
        'succeeded',
        'failed'
    ],
    title: 'LegacyImportJobStatus'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const ObligationComponentCreateSchema = {
    properties: {
        type: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Type'
        },
        label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Label'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'type',
        'label'
    ],
    title: 'ObligationComponentCreate'
} as const;

export const ObligationComponentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        obligation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Obligation Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'obligation_id',
        'type',
        'label',
        'amount',
        'source',
        'external_id',
        'metadata',
        'created_at',
        'updated_at'
    ],
    title: 'ObligationComponentPublic'
} as const;

export const ObligationComponentUpdateSchema = {
    properties: {
        type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ObligationComponentUpdate'
} as const;

export const ObligationComponentUpsertSchema = {
    properties: {
        type: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Type'
        },
        label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Label'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'type',
        'label'
    ],
    title: 'ObligationComponentUpsert'
} as const;

export const ObligationComponentsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ObligationComponentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ObligationComponentsPublic'
} as const;

export const ObligationCreateSchema = {
    properties: {
        category_code: {
            type: 'string',
            pattern: '^[A-Z]{4}$',
            title: 'Category Code'
        },
        period: {
            $ref: '#/components/schemas/BillingPeriodInput'
        },
        data_ready: {
            type: 'boolean',
            title: 'Data Ready',
            default: false
        },
        current_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        issue_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: [
        'category_code',
        'period'
    ],
    title: 'ObligationCreate'
} as const;

export const ObligationIntegrationUpdateSchema = {
    properties: {
        current_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        issue_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ObligationIntegrationUpdate',
    description: 'Values an API-key authenticated integration may update.'
} as const;

export const ObligationLifecycleSchema = {
    type: 'string',
    enum: [
        'draft',
        'collecting_data',
        'ready',
        'paid',
        'canceled',
        'error'
    ],
    title: 'ObligationLifecycle'
} as const;

export const ObligationNoteAppendSchema = {
    properties: {
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: [
        'text'
    ],
    title: 'ObligationNoteAppend'
} as const;

export const ObligationPeriodPublicSchema = {
    properties: {
        year: {
            type: 'integer',
            maximum: 9999,
            minimum: 1,
            title: 'Year'
        },
        month: {
            type: 'integer',
            maximum: 12,
            minimum: 1,
            title: 'Month'
        }
    },
    type: 'object',
    required: [
        'year',
        'month'
    ],
    title: 'ObligationPeriodPublic'
} as const;

export const ObligationPeriodTotalPublicSchema = {
    properties: {
        period: {
            $ref: '#/components/schemas/ObligationPeriodPublic'
        },
        total_obligation_count: {
            type: 'integer',
            title: 'Total Obligation Count'
        },
        unknown_amount_count: {
            type: 'integer',
            title: 'Unknown Amount Count'
        },
        is_complete: {
            type: 'boolean',
            title: 'Is Complete'
        },
        currency_summaries: {
            items: {
                $ref: '#/components/schemas/CurrencyPeriodTotalPublic'
            },
            type: 'array',
            title: 'Currency Summaries'
        }
    },
    type: 'object',
    required: [
        'period',
        'total_obligation_count',
        'unknown_amount_count',
        'is_complete',
        'currency_summaries'
    ],
    title: 'ObligationPeriodTotalPublic',
    description: 'One continuous chart point; unknown amounts are not represented as zero.'
} as const;

export const ObligationPeriodTotalsPublicSchema = {
    properties: {
        points: {
            items: {
                $ref: '#/components/schemas/ObligationPeriodTotalPublic'
            },
            type: 'array',
            title: 'Points'
        }
    },
    type: 'object',
    required: [
        'points'
    ],
    title: 'ObligationPeriodTotalsPublic'
} as const;

export const ObligationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        category_code: {
            type: 'string',
            title: 'Category Code'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        lifecycle: {
            $ref: '#/components/schemas/ObligationLifecycle'
        },
        period: {
            $ref: '#/components/schemas/ObligationPeriodPublic'
        },
        effective_value_source: {
            $ref: '#/components/schemas/EffectiveValueSourceMode'
        },
        current_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        amount_state: {
            $ref: '#/components/schemas/ValueState'
        },
        amount_source: {
            $ref: '#/components/schemas/CurrentValueSource'
        },
        issue_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Date'
        },
        issue_date_state: {
            $ref: '#/components/schemas/ValueState'
        },
        issue_date_source: {
            $ref: '#/components/schemas/CurrentValueSource'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        due_date_state: {
            $ref: '#/components/schemas/ValueState'
        },
        due_date_source: {
            $ref: '#/components/schemas/CurrentValueSource'
        },
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'ledger_id',
        'category_id',
        'category_code',
        'key',
        'name',
        'notes',
        'lifecycle',
        'period',
        'effective_value_source',
        'current_amount',
        'amount_state',
        'amount_source',
        'issue_date',
        'issue_date_state',
        'issue_date_source',
        'due_date',
        'due_date_state',
        'due_date_source',
        'currency',
        'paid_at',
        'created_at',
        'updated_at'
    ],
    title: 'ObligationPublic'
} as const;

export const ObligationUpdateSchema = {
    properties: {
        current_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        issue_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ObligationUpdate'
} as const;

export const ObligationsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ObligationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ObligationsPublic'
} as const;

export const PeriodCashflowPublicSchema = {
    properties: {
        period: {
            $ref: '#/components/schemas/ObligationPeriodPublic'
        },
        as_of_date: {
            type: 'string',
            format: 'date',
            title: 'As Of Date'
        },
        unknown_amount_count: {
            type: 'integer',
            title: 'Unknown Amount Count'
        },
        without_due_date_count: {
            type: 'integer',
            title: 'Without Due Date Count'
        },
        is_complete: {
            type: 'boolean',
            title: 'Is Complete'
        },
        currency_summaries: {
            items: {
                $ref: '#/components/schemas/CurrencyCashflowPublic'
            },
            type: 'array',
            title: 'Currency Summaries'
        }
    },
    type: 'object',
    required: [
        'period',
        'as_of_date',
        'unknown_amount_count',
        'without_due_date_count',
        'is_complete',
        'currency_summaries'
    ],
    title: 'PeriodCashflowPublic'
} as const;

export const PeriodPaymentSummaryPublicSchema = {
    properties: {
        period: {
            $ref: '#/components/schemas/ObligationPeriodPublic'
        },
        total_obligation_count: {
            type: 'integer',
            title: 'Total Obligation Count'
        },
        paid_obligation_count: {
            type: 'integer',
            title: 'Paid Obligation Count'
        },
        paid_percentage: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid Percentage'
        },
        unknown_amount_count: {
            type: 'integer',
            title: 'Unknown Amount Count'
        },
        is_complete: {
            type: 'boolean',
            title: 'Is Complete'
        },
        amount_summaries: {
            items: {
                $ref: '#/components/schemas/CurrencyPaymentSummaryPublic'
            },
            type: 'array',
            title: 'Amount Summaries'
        }
    },
    type: 'object',
    required: [
        'period',
        'total_obligation_count',
        'paid_obligation_count',
        'paid_percentage',
        'unknown_amount_count',
        'is_complete',
        'amount_summaries'
    ],
    title: 'PeriodPaymentSummaryPublic'
} as const;

export const RecurrenceUnitSchema = {
    type: 'string',
    enum: [
        'month',
        'year'
    ],
    title: 'RecurrenceUnit'
} as const;

export const SystemRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            $ref: '#/components/schemas/SystemRunStatus'
        },
        trigger: {
            $ref: '#/components/schemas/SystemRunTrigger'
        },
        effective_at: {
            type: 'string',
            format: 'date-time',
            title: 'Effective At'
        },
        timezone: {
            type: 'string',
            title: 'Timezone'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        summary: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        steps: {
            items: {
                $ref: '#/components/schemas/SystemRunStepPublic'
            },
            type: 'array',
            title: 'Steps'
        }
    },
    type: 'object',
    required: [
        'id',
        'status',
        'trigger',
        'effective_at',
        'timezone',
        'business_date',
        'summary',
        'error',
        'started_at',
        'finished_at'
    ],
    title: 'SystemRunPublic'
} as const;

export const SystemRunSkipReasonSchema = {
    type: 'string',
    enum: [
        'disabled',
        'manual_only',
        'not_due',
        'not_configured',
        'no_eligible_targets',
        'prerequisite_failed'
    ],
    title: 'SystemRunSkipReason'
} as const;

export const SystemRunStartSchema = {
    properties: {
        manual_task_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 100,
            title: 'Manual Task Names'
        }
    },
    type: 'object',
    title: 'SystemRunStart'
} as const;

export const SystemRunStatusSchema = {
    type: 'string',
    enum: [
        'running',
        'success',
        'partial_failure',
        'failure'
    ],
    title: 'SystemRunStatus'
} as const;

export const SystemRunStepPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_name: {
            type: 'string',
            title: 'Task Name'
        },
        ledger_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ledger Id'
        },
        status: {
            $ref: '#/components/schemas/SystemRunStepStatus'
        },
        skip_reason: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SystemRunSkipReason'
                },
                {
                    type: 'null'
                }
            ]
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        summary: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: [
        'id',
        'task_name',
        'ledger_id',
        'status',
        'skip_reason',
        'error',
        'summary',
        'started_at',
        'finished_at'
    ],
    title: 'SystemRunStepPublic'
} as const;

export const SystemRunStepStatusSchema = {
    type: 'string',
    enum: [
        'succeeded',
        'failed',
        'skipped'
    ],
    title: 'SystemRunStepStatus'
} as const;

export const SystemRunTaskPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        mode: {
            $ref: '#/components/schemas/TaskRunMode'
        }
    },
    type: 'object',
    required: [
        'name',
        'mode'
    ],
    title: 'SystemRunTaskPublic'
} as const;

export const SystemRunTriggerSchema = {
    type: 'string',
    enum: [
        'scheduled',
        'manual'
    ],
    title: 'SystemRunTrigger'
} as const;

export const SystemRunsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/SystemRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'SystemRunsPublic'
} as const;

export const TaskRunModeSchema = {
    type: 'string',
    enum: [
        'disabled',
        'manual_only',
        'scheduled'
    ],
    title: 'TaskRunMode'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'email',
        'id',
        'created_at'
    ],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const ValueStateSchema = {
    type: 'string',
    enum: [
        'unknown',
        'estimated',
        'confirmed',
        'overridden'
    ],
    title: 'ValueState'
} as const;
