/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutLedgersRouteImport } from './routes/_layout/ledgers'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLedgersIndexRouteImport } from './routes/_layout/ledgers.index'
import { Route as LayoutLedgersLedgerIdRouteImport } from './routes/_layout/ledgers.$ledgerId'
import { Route as LayoutLedgersLedgerIdAnalyticsRouteImport } from './routes/_layout/ledgers.$ledgerId.analytics'
import { Route as LayoutLedgersLedgerIdCategoriesRouteImport } from './routes/_layout/ledgers.$ledgerId.categories'
import { Route as LayoutLedgersLedgerIdSettingsRouteImport } from './routes/_layout/ledgers.$ledgerId.settings'
import { Route as LayoutLedgersLedgerIdSystemRunRouteImport } from './routes/_layout/ledgers.$ledgerId.system-run'
import { Route as LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRouteImport } from './routes/_layout/ledgers.$ledgerId.categories.$categoryId.custom-fields'
import { Route as LayoutLedgersLedgerIdCategoriesCategoryIdDataRouteImport } from './routes/_layout/ledgers.$ledgerId.categories.$categoryId.data'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLedgersRoute = LayoutLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLedgersIndexRoute = LayoutLedgersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutLedgersRoute,
} as any)
const LayoutLedgersLedgerIdRoute = LayoutLedgersLedgerIdRouteImport.update({
  id: '/$ledgerId',
  path: '/$ledgerId',
  getParentRoute: () => LayoutLedgersRoute,
} as any)
const LayoutLedgersLedgerIdAnalyticsRoute =
  LayoutLedgersLedgerIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => LayoutLedgersLedgerIdRoute,
  } as any)
const LayoutLedgersLedgerIdCategoriesRoute =
  LayoutLedgersLedgerIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LayoutLedgersLedgerIdRoute,
  } as any)
const LayoutLedgersLedgerIdSettingsRoute =
  LayoutLedgersLedgerIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutLedgersLedgerIdRoute,
  } as any)
const LayoutLedgersLedgerIdSystemRunRoute =
  LayoutLedgersLedgerIdSystemRunRouteImport.update({
    id: '/system-run',
    path: '/system-run',
    getParentRoute: () => LayoutLedgersLedgerIdRoute,
  } as any)
const LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute =
  LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRouteImport.update({
    id: '/$categoryId/custom-fields',
    path: '/$categoryId/custom-fields',
    getParentRoute: () => LayoutLedgersLedgerIdCategoriesRoute,
  } as any)
const LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute =
  LayoutLedgersLedgerIdCategoriesCategoryIdDataRouteImport.update({
    id: '/$categoryId/data',
    path: '/$categoryId/data',
    getParentRoute: () => LayoutLedgersLedgerIdCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/ledgers': typeof LayoutLedgersRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/ledgers/$ledgerId': typeof LayoutLedgersLedgerIdRouteWithChildren
  '/ledgers/': typeof LayoutLedgersIndexRoute
  '/ledgers/$ledgerId/analytics': typeof LayoutLedgersLedgerIdAnalyticsRoute
  '/ledgers/$ledgerId/categories': typeof LayoutLedgersLedgerIdCategoriesRouteWithChildren
  '/ledgers/$ledgerId/settings': typeof LayoutLedgersLedgerIdSettingsRoute
  '/ledgers/$ledgerId/system-run': typeof LayoutLedgersLedgerIdSystemRunRoute
  '/ledgers/$ledgerId/categories/$categoryId/custom-fields': typeof LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute
  '/ledgers/$ledgerId/categories/$categoryId/data': typeof LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/ledgers/$ledgerId': typeof LayoutLedgersLedgerIdRouteWithChildren
  '/ledgers': typeof LayoutLedgersIndexRoute
  '/ledgers/$ledgerId/analytics': typeof LayoutLedgersLedgerIdAnalyticsRoute
  '/ledgers/$ledgerId/categories': typeof LayoutLedgersLedgerIdCategoriesRouteWithChildren
  '/ledgers/$ledgerId/settings': typeof LayoutLedgersLedgerIdSettingsRoute
  '/ledgers/$ledgerId/system-run': typeof LayoutLedgersLedgerIdSystemRunRoute
  '/ledgers/$ledgerId/categories/$categoryId/custom-fields': typeof LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute
  '/ledgers/$ledgerId/categories/$categoryId/data': typeof LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/ledgers': typeof LayoutLedgersRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/ledgers/$ledgerId': typeof LayoutLedgersLedgerIdRouteWithChildren
  '/_layout/ledgers/': typeof LayoutLedgersIndexRoute
  '/_layout/ledgers/$ledgerId/analytics': typeof LayoutLedgersLedgerIdAnalyticsRoute
  '/_layout/ledgers/$ledgerId/categories': typeof LayoutLedgersLedgerIdCategoriesRouteWithChildren
  '/_layout/ledgers/$ledgerId/settings': typeof LayoutLedgersLedgerIdSettingsRoute
  '/_layout/ledgers/$ledgerId/system-run': typeof LayoutLedgersLedgerIdSystemRunRoute
  '/_layout/ledgers/$ledgerId/categories/$categoryId/custom-fields': typeof LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute
  '/_layout/ledgers/$ledgerId/categories/$categoryId/data': typeof LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/ledgers'
    | '/settings'
    | '/ledgers/$ledgerId'
    | '/ledgers/'
    | '/ledgers/$ledgerId/analytics'
    | '/ledgers/$ledgerId/categories'
    | '/ledgers/$ledgerId/settings'
    | '/ledgers/$ledgerId/system-run'
    | '/ledgers/$ledgerId/categories/$categoryId/custom-fields'
    | '/ledgers/$ledgerId/categories/$categoryId/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/settings'
    | '/'
    | '/ledgers/$ledgerId'
    | '/ledgers'
    | '/ledgers/$ledgerId/analytics'
    | '/ledgers/$ledgerId/categories'
    | '/ledgers/$ledgerId/settings'
    | '/ledgers/$ledgerId/system-run'
    | '/ledgers/$ledgerId/categories/$categoryId/custom-fields'
    | '/ledgers/$ledgerId/categories/$categoryId/data'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/ledgers'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/ledgers/$ledgerId'
    | '/_layout/ledgers/'
    | '/_layout/ledgers/$ledgerId/analytics'
    | '/_layout/ledgers/$ledgerId/categories'
    | '/_layout/ledgers/$ledgerId/settings'
    | '/_layout/ledgers/$ledgerId/system-run'
    | '/_layout/ledgers/$ledgerId/categories/$categoryId/custom-fields'
    | '/_layout/ledgers/$ledgerId/categories/$categoryId/data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ledgers': {
      id: '/_layout/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LayoutLedgersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ledgers/': {
      id: '/_layout/ledgers/'
      path: '/'
      fullPath: '/ledgers/'
      preLoaderRoute: typeof LayoutLedgersIndexRouteImport
      parentRoute: typeof LayoutLedgersRoute
    }
    '/_layout/ledgers/$ledgerId': {
      id: '/_layout/ledgers/$ledgerId'
      path: '/$ledgerId'
      fullPath: '/ledgers/$ledgerId'
      preLoaderRoute: typeof LayoutLedgersLedgerIdRouteImport
      parentRoute: typeof LayoutLedgersRoute
    }
    '/_layout/ledgers/$ledgerId/analytics': {
      id: '/_layout/ledgers/$ledgerId/analytics'
      path: '/analytics'
      fullPath: '/ledgers/$ledgerId/analytics'
      preLoaderRoute: typeof LayoutLedgersLedgerIdAnalyticsRouteImport
      parentRoute: typeof LayoutLedgersLedgerIdRoute
    }
    '/_layout/ledgers/$ledgerId/categories': {
      id: '/_layout/ledgers/$ledgerId/categories'
      path: '/categories'
      fullPath: '/ledgers/$ledgerId/categories'
      preLoaderRoute: typeof LayoutLedgersLedgerIdCategoriesRouteImport
      parentRoute: typeof LayoutLedgersLedgerIdRoute
    }
    '/_layout/ledgers/$ledgerId/settings': {
      id: '/_layout/ledgers/$ledgerId/settings'
      path: '/settings'
      fullPath: '/ledgers/$ledgerId/settings'
      preLoaderRoute: typeof LayoutLedgersLedgerIdSettingsRouteImport
      parentRoute: typeof LayoutLedgersLedgerIdRoute
    }
    '/_layout/ledgers/$ledgerId/system-run': {
      id: '/_layout/ledgers/$ledgerId/system-run'
      path: '/system-run'
      fullPath: '/ledgers/$ledgerId/system-run'
      preLoaderRoute: typeof LayoutLedgersLedgerIdSystemRunRouteImport
      parentRoute: typeof LayoutLedgersLedgerIdRoute
    }
    '/_layout/ledgers/$ledgerId/categories/$categoryId/custom-fields': {
      id: '/_layout/ledgers/$ledgerId/categories/$categoryId/custom-fields'
      path: '/$categoryId/custom-fields'
      fullPath: '/ledgers/$ledgerId/categories/$categoryId/custom-fields'
      preLoaderRoute: typeof LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRouteImport
      parentRoute: typeof LayoutLedgersLedgerIdCategoriesRoute
    }
    '/_layout/ledgers/$ledgerId/categories/$categoryId/data': {
      id: '/_layout/ledgers/$ledgerId/categories/$categoryId/data'
      path: '/$categoryId/data'
      fullPath: '/ledgers/$ledgerId/categories/$categoryId/data'
      preLoaderRoute: typeof LayoutLedgersLedgerIdCategoriesCategoryIdDataRouteImport
      parentRoute: typeof LayoutLedgersLedgerIdCategoriesRoute
    }
  }
}

interface LayoutLedgersLedgerIdCategoriesRouteChildren {
  LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute: typeof LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute
  LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute: typeof LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute
}

const LayoutLedgersLedgerIdCategoriesRouteChildren: LayoutLedgersLedgerIdCategoriesRouteChildren =
  {
    LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute:
      LayoutLedgersLedgerIdCategoriesCategoryIdCustomFieldsRoute,
    LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute:
      LayoutLedgersLedgerIdCategoriesCategoryIdDataRoute,
  }

const LayoutLedgersLedgerIdCategoriesRouteWithChildren =
  LayoutLedgersLedgerIdCategoriesRoute._addFileChildren(
    LayoutLedgersLedgerIdCategoriesRouteChildren,
  )

interface LayoutLedgersLedgerIdRouteChildren {
  LayoutLedgersLedgerIdAnalyticsRoute: typeof LayoutLedgersLedgerIdAnalyticsRoute
  LayoutLedgersLedgerIdCategoriesRoute: typeof LayoutLedgersLedgerIdCategoriesRouteWithChildren
  LayoutLedgersLedgerIdSettingsRoute: typeof LayoutLedgersLedgerIdSettingsRoute
  LayoutLedgersLedgerIdSystemRunRoute: typeof LayoutLedgersLedgerIdSystemRunRoute
}

const LayoutLedgersLedgerIdRouteChildren: LayoutLedgersLedgerIdRouteChildren = {
  LayoutLedgersLedgerIdAnalyticsRoute: LayoutLedgersLedgerIdAnalyticsRoute,
  LayoutLedgersLedgerIdCategoriesRoute:
    LayoutLedgersLedgerIdCategoriesRouteWithChildren,
  LayoutLedgersLedgerIdSettingsRoute: LayoutLedgersLedgerIdSettingsRoute,
  LayoutLedgersLedgerIdSystemRunRoute: LayoutLedgersLedgerIdSystemRunRoute,
}

const LayoutLedgersLedgerIdRouteWithChildren =
  LayoutLedgersLedgerIdRoute._addFileChildren(
    LayoutLedgersLedgerIdRouteChildren,
  )

interface LayoutLedgersRouteChildren {
  LayoutLedgersLedgerIdRoute: typeof LayoutLedgersLedgerIdRouteWithChildren
  LayoutLedgersIndexRoute: typeof LayoutLedgersIndexRoute
}

const LayoutLedgersRouteChildren: LayoutLedgersRouteChildren = {
  LayoutLedgersLedgerIdRoute: LayoutLedgersLedgerIdRouteWithChildren,
  LayoutLedgersIndexRoute: LayoutLedgersIndexRoute,
}

const LayoutLedgersRouteWithChildren = LayoutLedgersRoute._addFileChildren(
  LayoutLedgersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutLedgersRoute: typeof LayoutLedgersRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutLedgersRoute: LayoutLedgersRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
